from maat import Value
from .exceptions import GenericException
import rlp
import sha3


def twos_complement_convert(arg: int, bits: int) -> int:
    """Takes an python integer and determines it's two's complement value
    in a given bit size

    :param arg: value to convert, interpreted as an unsigned value
    :param bits: bit length of 'arg'

    :return: two's complement integer of `arg` on `bits` length
    """
    if arg < 0:
        raise GenericException("Expected a positive value")
    elif arg >= (1 << bits):
        raise GenericException(f"Value {arg} too big to fit on {bits} bits")

    if arg & (1 << (bits - 1)) == 0:
        # Positive number
        return arg
    else:
        # Negative number
        return arg - (1 << bits)


def int_to_bool(arg: int) -> bool:
    """Takes a python integer and converts it to a boolean value.

    :param arg: value to convert, integer representing a bool

    :return False if arg is 0, True otherwise"""

    if arg < 0:
        raise GenericException("Expected a positive value")

    return arg != 0


def compute_new_contract_addr(sender: int, nonce: int) -> int:
    """Compute a new contract address as generated by the CREATE instruction
    originating from 'sender' with nonce 'nonce'"""

    k = sha3.keccak_256()
    k.update(rlp.encode([sender, nonce]))
    digest = k.digest()[12:]
    return int.from_bytes(digest, "big")
