name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # needs to run only on pull_request
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Lint
      run: |
        pip install -e .[lint]
        black --version
        black --diff --check optik

  hybrid-echidna:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install solc 0.7.1
      run: |
        pip3 install solc-select
        solc-select install 0.7.1 && solc-select use 0.7.1
    - name: Install echidna
      run: |
        wget -O echidna.tar.gz -c https://github.com/crytic/echidna/releases/download/v2.0.2/echidna-test-2.0.2-Ubuntu-18.04.tar.gz
        sudo tar xvf echidna.tar.gz -C /usr/bin/
    - name: Run tests
      run: |
        pip install -e .[tests]
        python3 -m pytest tests/echidna