name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # needs to run only on pull_request
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Lint
      run: |
        pip install -e .[lint]
        black --version
        black --diff --check optik

  hybrid-echidna:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run tests
      run: |
        pip install -e .[tests]
        python3 -m pytest tests/echidna