name: Deploy Python package

on:
  # Run on official releases (bump minor or major version number)
  release:
    types:
      - published

jobs:

  build_project:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7

    steps:
      # Configure Python
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Dependencies
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install build
        
      # Build package
      - name: Build package
        run: |
          python -m build


  upload_to_pypi:
    name: upload package to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheels_linux, build_wheels_macos]

    steps:
      
      -name: "Upload"
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        # upload to testpypi for now
        repository_url: https://test.pypi.org/simple/
