name: "Deploy Python package"

on:
  # Run on official releases (bump minor or major version number)
  release:
    types:
      - published
  push:
    branches:
      python-packaging


jobs:

  build_and_publish:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7

    steps:
    # Configure Python
    - uses: actions/checkout@v2
    - name: "Set up python ${{ matrix.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Dependencies
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        pip install build
    # Build package
    - name: Build package
      run: |
        python -m build
    # Upload package to PyPI (currently testPyPI)
    - name: Upload package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        # upload to testpypi for now
        repository_url: https://test.pypi.org/simple/
